### ISSUE TITLE
Pronouns support

### ISSUE THREAD

**Issue by cfytrok** [bjascob/LemmInflect#15]
Please add pronouns support.
lemminflect.getAllLemmas('his') returns {}

**Comment by bjascob** [comment]
I'd suggest adding logic to your code so that if `lemminflect.getAllLemmas()` returns '{}' to just use the original word. This method does a lookup and the raw NIH dateset which for some reason doesn't appear to contain any pronouns (except "I").

I will add the following pronouns... `he, him, her, it, me, she, them, they, us, we, you`.  Note that `lemminflect.getAllLemmas('I')` already returns `{'NOUN': ('I',)}`
--> Put updates in `resources/lemma_overrides.csv` or hard-code them in `LemmaLUCodec.py::load()`.

**Comment by bjascob** [comment]
43f9358a960dcc89de5429437e690af6b3bf8896 add the above to `lemma_overrides.csv` and test cases in `LemmatizerTests.py`

Need to review and push update to pypi

**Comment by bjascob** [comment]
Updates added in Release 0.2.3
